name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        node_version: [lts/-1, lts/*, latest, 22.13.1,  22.13.0, 22.12.0, 22.11.0, 22.10.0, 22.9.0, 22.8.0, 22.7.0, 22.6.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: node --loader ts-node/esm src/main.ts
